apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
  namespace: vehicle-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z database-service 5432; do echo waiting for database; sleep 2; done;']
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
      - name: data-processor
        image: data-processor:latest
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: DATABASE_HOST
          value: "database-service"
        - name: DATABASE_NAME
          value: "vehicle_monitoring"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "your_password"
        - name: DATABASE_PORT
          value: "5432"
