apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: vehicle-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672  # AMQP порт
        - containerPort: 15672 # Management UI порт
