apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
  namespace: vehicle-monitoring
spec:
  selector:
    app: data-collector
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
